apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 25
      targetPort: smtp
      protocol: TCP
      name: smtp
      {{ if .Values.smtpNodePort }}
      nodePort:  {{ .Values.smtpNodePort }}
      {{ end }}
  selector:
    release: {{ .Release.Name }}
